const USER_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  USER: 'USER',
  ADMIN: 'ADMIN',
};

const LEAD_TYPE = {
  SOLAR_RESIDENTIAL: 'SOLAR_RESIDENTIAL',
  ROOFING: 'ROOFING',
  SOLAR_COMMERCIAL: 'SOLAR_COMMERCIAL',
};

const EXCLUSIVITY = {
  EXCLUSIVE: 'EXCLUSIVE',
  NON_EXCLUSIVE: 'NON_EXCLUSIVE',
  SHARED: 'SHARED',
  WARM_TRANSFER: 'WARM_TRANSFER',
  APPOINTMENT: 'APPOINTMENT',
};
const STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  REJECTED: 'REJECTED',
};

module.exports = {
  USER_ROLE,
  LEAD_TYPE,
  EXCLUSIVITY,
  STATUS,
};
